### PR TITLE
Add simple JWT demo

### PR DESCRIPTION
**Pull request by GIANTCRAB**
This PR will add a simple tokens demo through the tokenscontroller.

### CODE REVIEW

**Comment by lindyhopchris** [comment]
Thanks! Will take a look soon when I get a chance between work stuff.

**Comment by lindyhopchris** [comment]
Hi! Have had a look at this. The main problem I need to sort out is the branches have diverged. Can you give me permission to push to your fork? Then I sort out the merge conflicts for you as I think that'll be easier than you doing it.

https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by GIANTCRAB** [comment]
Hi, I've checked the `Allow edits from maintainers. ` and also added you as collaborator to my repo.

**Comment by lindyhopchris** [comment]
Closing this because the `5.6` branch now uses `laravel/passport` for authentication.

**Pull request closed without merging**
